@startuml 1

玩家 --> (注册)
玩家 --> (登录)
玩家 --> (创建角色)
玩家 --> (删除角色)
玩家 --> (进入游戏)

管理员 --> (登录)
管理员 --> (创建角色)
管理员 --> (删除角色)
管理员 --> (进入游戏)
管理员 --> (管理游戏)

(管理游戏) <.. (删除玩家): <<extend>>
(管理游戏) <.. (修改角色): <<extend>>

@enduml