@startuml 1

玩家 --> (移动)
玩家 --> (购买/出售)
玩家 --> (进入副本)
玩家 -> (与其它玩家交互)
玩家 --> (转移物品（仓库、背包）)

管理员 -> (与其它玩家交互)
管理员 --> (移动)
管理员 --> (购买/出售)
管理员 --> (进入副本)
管理员 --> (转移物品（仓库、背包）)
管理员 --> (管理游戏)


(管理游戏) <.. (赠送/拿走物品): <<extend>>
(管理游戏) <.. (修改角色): <<extend>>

@enduml