@startuml 7

actor 玩家
boundary 前端
control 后端
database 数据库

玩家 -> 前端: 输入相关信息
前端 -> 后端: 验证并传递注册信息
后端 -> 数据库: 存入信息
前端 <- 后端: 注册成功

玩家 -> 前端: 登录
前端 -> 后端: 发送登陆信息
后端 -> 数据库: 查询用户
后端 <- 数据库: 返回用户信息
前端 <- 后端: 登录成功

玩家 -> 前端: 设计角色
前端 -> 后端: 角色信息
后端 -> 数据库: 存入角色
前端 <- 后端: 创建完成

玩家 -> 前端: 进入游戏

@enduml