@startuml 8

actor 玩家1
actor 玩家2
boundary 前端
control 后端
database 数据库

玩家1 -> 前端: 请求与玩家2组队
前端 -> 后端: 传递组队请求
后端 -> 数据库: 将请求存入玩家2消息盒

前端 <- 后端: 展示组队请求

玩家2 -> 前端: 接受组队邀请
前端 -> 后端: 传递接受信息
后端 -> 数据库: 添加组队信息

前端 <- 后端: 组队成功

@enduml