@startuml 9

actor 玩家
entity 第三方支付
boundary 前端
control 后端
database 数据库

玩家 -> 前端: 请求充值
前端 -> 后端: 发送充值请求
后端 -> 数据库: 启动事务

第三方支付 <- 后端: 转到充值界面

玩家 -> 第三方支付: 进行支付

第三方支付 -> 后端: 支付结果

后端 -> 数据库: 修改数据
后端 -> 数据库: 结束事务


前端 <- 后端: 充值成功

@enduml